name: Android_APK_Yaratish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: JDK 17-ni sozlash
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Majburiy Build (Xatolarni chetlab o'tish)
        run: |
          rm -f gradlew gradlew.bat
          # Bu yerda biz Gradle-ga keshdan foydalanmaslikni va 
          # xatolarga qaramay yig'ishni buyuramiz
          gradle assembleDebug \
            --no-daemon \
            --no-configure-on-demand \
            -Pandroid.nonTransitiveRClass=false \
            -Dorg.gradle.jvmargs="-Xmx4g" \
            -x test

      - name: APK-ni saqlash
        uses: actions/upload-artifact@v4
        with:
          name: TubeMe-Build
          path: app/build/outputs/apk/debug/*.apk
