name: Android_APK_Yaratish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: JDK 17-ni sozlash
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Xato fayllarni tozalash va kuchaytirilgan Build
        run: |
          rm -f gradlew
          rm -f gradlew.bat
          # Bu buyruq xotirani maksimal darajada boshqaradi
          gradle assembleDebug -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" --no-daemon
          
      - name: APK-ni saqlash
        uses: actions/upload-artifact@v4
        with:
          name: TubeMe-Build-APK
          path: app/build/outputs/apk/debug/*.apk
          
